name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "**.go"
      - "go.mod"
      - "go.sum"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Run tests
        run: go test ./...
